.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "UPDATE\-IMG" "8" "February 2026" "Slide"
.SH "NAME"
\fBupdate\-img\fR
.SH "NAME"
update\-img \- Update a backup image with moocbt COW file\.
.SH "SYNOPSIS"
\fBupdate\-img <snapshot device> <cow file> <image file>\fR
.SH "DESCRIPTION"
\fBupdate\-img\fR is a simple tool to efficiently update backup images made by the moocbt kernel module\. It uses the leftover COW file from moocbt's incremental state to efficiently update an existing backup image\. See the man page on \fBmoo\fR for an example use case\.
.SS "EXAMPLES"
\fB# update\-img /dev/moocbt4 /var/backup/moocow1 /mnt/data/backup\-img\fR
.P
This command will update a previously backed up snapshot \fB/mnt/data/backup\-img\fR with the changed blocks indicated by \fB/var/backup/moocow1\fR from \fB/dev/moocbt4\fR\.
.P
NOTE: \fB<snapshot device>\fR MUST be the NEXT snapshot after the one that \fB<image file>\fR was copied from\.
.SH "BUGS"
.SH "AUTHORS"
Tom Caputi (tcaputi@datto\.com)
.P
Slide (it@slide\.tech)
.SH "COPYRIGHT"
Additional contributions by Slide are Copyright (C) 2026 Project Orca Inc
