#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only

# ./genconfig.sh - generate C header for setting the correct preprocessor definitions for the kernel version
# Usage ./genconfig.sh <kernel version> <make flags>
# The make flags are used for determining concurrency for the feature tests, it pulls out the value of the -j flag.
# ./genconfig.sh `uname -r` "-j4", four threads for running feature tests
# ./genconfig.sh `uname -r` "-i -j4 -d", doesn't care about other flags present

SRC_DIR=$(dirname "$0")
OUTPUT_FILE=$SRC_DIR/kernel-config.h
FEATURE_TEST_DIR="$SRC_DIR/configure-tests/feature-tests"
FEATURE_TEST_FILES="$FEATURE_TEST_DIR/*.c"
SYMBOL_TESTS_FILE="$SRC_DIR/configure-tests/symbol-tests"
KERNEL_VERSION=$(uname -r)
MAX_THREADS=$(echo "$2" | sed -E 's/.*-j\s*([0-9]+).*/\1/')
if ! [[ "$MAX_THREADS" =~ '^[0-9]+$' ]]; then # if there was no -j flag provided, default to the number of processors
	MAX_THREADS=$(getconf _NPROCESSORS_ONLN)
fi

if [ ! -z "$1" ]; then
	KERNEL_VERSION="$1"
fi

SYSTEM_MAP_FILE_VARIANTS=(
	"/lib/modules/${KERNEL_VERSION}/System.map"
	"/boot/System.map-${KERNEL_VERSION}"
	"/usr/lib/debug/boot/System.map-${KERNEL_VERSION}"
)

for FILE_VARIANT in ${SYSTEM_MAP_FILE_VARIANTS[@]}; do
	if [ -f "$FILE_VARIANT" ] && grep -q '__per_cpu_start' "$FILE_VARIANT"; then
		SYSTEM_MAP_FILE="$FILE_VARIANT"
		break
	fi
done

if [ -z "$SYSTEM_MAP_FILE" ]; then
	if [ "$(uname -r)" == "${KERNEL_VERSION}" ]; then
		echo "System.map file not found for current kernel version; using /proc/kallsyms"
		SYSTEM_MAP_FILE="/proc/kallsyms"
	else
		echo "System.map file not found for kernel version ${KERNEL_VERSION}"
		exit 1
	fi
fi

echo "using System.map file: ${SYSTEM_MAP_FILE}"
echo "generating configurations for kernel-${KERNEL_VERSION}"

MANIFEST_FILE="$(mktemp)"
rm -f $OUTPUT_FILE

echo "//The values in this file should be generated by the build process. Do not alter." >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "#ifndef MOOCBT_KERNEL_CONFIG_H" >> $OUTPUT_FILE
echo "#define MOOCBT_KERNEL_CONFIG_H" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

make -s -C $FEATURE_TEST_DIR clean KERNELVERSION=$KERNEL_VERSION

run_one_test() {
	local TEST="$(basename $1 .c)"
	local MACRO_NAME="HAVE_$(echo ${TEST} | awk '{print toupper($0)}')"
	local PREFIX="performing configure test: $MACRO_NAME -"
	if make -C $FEATURE_TEST_DIR TEST=$TEST KERNELVERSION=$KERNEL_VERSION &>/dev/null ; then
		echo "$PREFIX present"
		echo "#define $MACRO_NAME" >> $OUTPUT_FILE
		printf '\tFEATURE("%s", 1) \\\n' "$TEST" >> $MANIFEST_FILE
	else
		echo "$PREFIX not present"
		printf '\tFEATURE("%s", 0) \\\n' "$TEST" >> $MANIFEST_FILE
	fi
}
export -f run_one_test
export FEATURE_TEST_DIR
export KERNEL_VERSION
export OUTPUT_FILE
export MANIFEST_FILE

ls -1 -q $FEATURE_TEST_FILES | xargs -P "$MAX_THREADS" -d"\n" -I {} bash -c 'run_one_test {}'

make -s -C $FEATURE_TEST_DIR clean KERNELVERSION=$KERNEL_VERSION

echo "" >> $OUTPUT_FILE
echo "#define MOOCBT_BUILD_FEATURE_LIST(FEATURE) \\" >> $OUTPUT_FILE
LC_ALL=C sort "$MANIFEST_FILE" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
rm -f "$MANIFEST_FILE"

SYMBOL_MANIFEST_FILE="$(mktemp)"

while read SYMBOL_NAME; do
	if [ -z "$SYMBOL_NAME" ]; then
		continue
	fi

	echo "performing $SYMBOL_NAME lookup"
	MACRO_NAME="$(echo ${SYMBOL_NAME} | awk '{print toupper($0)}')_ADDR"
	SYMBOL_ADDR=$(grep " ${SYMBOL_NAME}$" "${SYSTEM_MAP_FILE}" | awk '{print $1}')
	if [ -z "$SYMBOL_ADDR" ]; then
		SYMBOL_ADDR="0"
	fi
	echo "#define $MACRO_NAME 0x$SYMBOL_ADDR" >> $OUTPUT_FILE
	if [ "$SYMBOL_ADDR" != "0" ]; then
		PRESENT=1
	else
		PRESENT=0
	fi
	printf '\tSYMBOL("%s", %d) \\\n' "$SYMBOL_NAME" "$PRESENT" >> $SYMBOL_MANIFEST_FILE
done < $SYMBOL_TESTS_FILE

# Detect whether the CPU building the module supports IBT.
#
# Use "FORCE_IBT=1" or "FORCE_IBT=0" environment variables to force enable
# building with or without IBT support respectively. Leave the environment
# variable unset to fallback to detecting with the current system's CPU.
case "$FORCE_IBT" in
	1)
		echo "performing configure test: BUILD_CPU_HAS_IBT_FORCE_ON - present"
		echo "#define BUILD_CPU_HAS_IBT_FORCE_ON" >> $OUTPUT_FILE
		;;
	0)
		echo "performing configure test: BUILD_CPU_HAS_IBT_FORCE_OFF - present"
		echo "#define BUILD_CPU_HAS_IBT_FORCE_OFF" >> $OUTPUT_FILE
		;;
	*)
		if [ -n "$FORCE_IBT" ]; then
			echo "warning: ignoring invalid FORCE_IBT='$FORCE_IBT' (expected 0 or 1)"
		fi
		;;
esac

if grep -qw ibt /proc/cpuinfo 2>/dev/null; then
	echo "performing configure test: BUILD_CPU_HAS_IBT - present"
	echo "#define BUILD_CPU_HAS_IBT" >> $OUTPUT_FILE
else
	echo "performing configure test: BUILD_CPU_HAS_IBT - not present"
fi

echo "" >> $OUTPUT_FILE
echo "#define MOOCBT_BUILD_SYMBOL_LIST(SYMBOL) \\" >> $OUTPUT_FILE
LC_ALL=C sort "$SYMBOL_MANIFEST_FILE" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
rm -f "$SYMBOL_MANIFEST_FILE"

echo "" >> $OUTPUT_FILE
echo "#endif" >> $OUTPUT_FILE

